### ISSUE TITLE
Plans to contine??

### ISSUE THREAD

**Issue by Mr-HaleYa** [yourjelly/home-assistant_owie#3]
I think this project would be awesome to have! Would love to see it keep going and be added in via hacs.
Been a while since this has been touched <s>and it seems to no longer work</s>...
Hope you can continue building this out!

**Comment by yourjelly** [comment]
I've not done much to develop it further, but it's working for me what
issue are you having with it.

**Comment by Mr-HaleYa** [comment]
<img width="658" alt="image" src="https://github.com/yourjelly/home-assistant_owie/assets/42821995/8b11c551-d6a0-494b-8785-63c9c6085cf1">
<img width="644" alt="image" src="https://github.com/yourjelly/home-assistant_owie/assets/42821995/bc179f49-e134-4af2-8e4f-f23ba7602477">

I get these two warnings on reboot

<img width="442" alt="image" src="https://github.com/yourjelly/home-assistant_owie/assets/42821995/c1d824cb-cbd9-4154-8b31-4c99e4ebe60e">

Placed the folder in the right place

<img width="203" alt="image" src="https://github.com/yourjelly/home-assistant_owie/assets/42821995/2867c7c6-757d-48a7-96fd-fdef73052b3e">

And this is in my sensors.yaml

<img width="366" alt="image" src="https://github.com/yourjelly/home-assistant_owie/assets/42821995/883ea390-f27e-4953-b6d8-3027a5785854">
<img width="366" alt="image" src="https://github.com/yourjelly/home-assistant_owie/assets/42821995/98f9b11f-5394-4393-87a9-5dc80a8704be">

But sensors never update... 

<img width="486" alt="image" src="https://github.com/yourjelly/home-assistant_owie/assets/42821995/5da1a43e-527a-40eb-93f6-7083e3c466f9">

configured the OWIE to connect to my network and I've seen it online in my router settings

**Comment by yourjelly** [comment]
if you navigate to 192.168.50.60 on your home network do you see owie?
![image](https://github.com/yourjelly/home-assistant_owie/assets/26312697/a5df87f2-1971-4327-b85a-0ee421e73f46)

**Comment by Mr-HaleYa** [comment]
<img width="649" alt="image" src="https://github.com/yourjelly/home-assistant_owie/assets/42821995/fe391928-72c4-4766-b9d3-2dc4accef0d4">

Got it working now 

<img width="320" alt="image" src="https://github.com/yourjelly/home-assistant_owie/assets/42821995/c4d7d3af-7d53-4b66-9a01-d28e9d94957d">

Had to plug in and reflash the OWIE board, something about changing settings multiple times made it unstable to the point it would not connect to the network and would reboot every couple of minutes randomly...

**Comment by Mr-HaleYa** [comment]
After thinking a bit more I don't see too many things to change/add.

I do like the Idea of it being in Hacs with an easy and clean frontend setup.

Solving the issue of losing battery value on reboot would be a nice fix.

A boolean of whether the Owie is connected to the network or not would be nice to have built into this, it is doable in many other ways but makes sense. Since you're collecting packets on a timer if it misses 3 or more then consider it disconnected. Could then have it sample for packets less frequent, i.e. 5 min. At which point, it would realize it's online and go back to fast sampling, saving unneeded overhead. 

Would like to get the cell voltages and temps in as well. Pretty much all the data from the Owie board would be nice to have and let users do what they want with it. I could totally go ham on making a nice UI that would pretty much mirror OWIE in HASS for something like my wall-mount tablet to just check stats when heading out the door. With that, I could have it give me alerts or whatever if something weird like a cell drifted or a temp warning when charging.

---
Unrelated but curious, do you think it's possible to connect the OW directly to HASS via BT or use an ESP32 as a middleman to connect and then relay the data in? I would love to just have all the stats in HASS. Looking at how OWCE hasn't even been able to get the board to connect to their app directly I hesitate to think this would work.

**Comment by yourjelly** [comment]
> Solving the issue of losing battery value on reboot would be a nice fix. 

Yeah, although with a stable Hass setup that issue is less prevelant


> A boolean of whether the Owie is connected to the network or not would be nice to have built into this, it is doable in many other ways but makes sense. Since you're collecting packets on a timer if it misses 3 or more then consider it disconnected. Could then have it sample for packets less frequent, i.e. 5 min. At which point, it would realize it's online and go back to fast sampling, saving unneeded overhead.

There is a way to have Hass handle the requests and do all that stuff natively but wasn't able to figure it out last I tried.

 
> Would like to get the cell voltages and temps in as well. Pretty much all the data from the Owie board would be nice to have and let users do what they want with it. I could totally go ham on making a nice UI that would pretty much mirror OWIE in HASS for something like my wall-mount tablet to just check stats when heading out the door. With that, I could have it give me alerts or whatever if something weird like a cell drifted or a temp warning when charging.

This is probably the easiest add but I was reading that having a lot of additional attributes to a sensor isn't best practice for Hass databases and got lost looking for another solution


> Unrelated but curious, do you think it's possible to connect the OW directly to HASS via BT or use an ESP32 as a middleman to connect and then relay the data in? I would love to just have all the stats in HASS. Looking at how OWCE hasn't even been able to get the board to connect to their app directly I hesitate to think this would work.

I'm not sure about this, the board would need to be on and can only connect to one bluetooth device at a time. I wouldnt want Hass blocking my phone from connecting to the board. There are ways to connect directly tho with rewheel, looking into the code for rewheel and OWCE might get you a solution.

**Comment by yourjelly** [comment]
Actually, my Pint's BMS just fried itself. So any lingering interest in continued development of this has been lost for me.

**Comment by Mr-HaleYa** [comment]
Can I take the project over then?

**Comment by yourjelly** [comment]
If you would like to; you're more than welcome to.
You just might have to tell me how to do that, cuz I am still v new to all this code & git stuff w/ no formal training.

**Comment by Mr-HaleYa** [comment]
Under your repository name, click Settings At the bottom of the page, in the "Danger Zone" section, click Transfer.

**Comment by yourjelly** [comment]
Can't transfer while you have a fork annoyingly enough, added you as a contributor so you can merge all your changes and close your fork then I can transfer
